# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igeQaey-o0lCN9CvoQM9MUq0Lr3QgPD6
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
import warnings
warnings.filterwarnings("ignore")

# 1. Leer el archivo
file_path = '21.1.xlsx'  # Asegúrate de que esté en el mismo directorio si estás en local
df = pd.read_excel(file_path)

# 2. Limpiar los datos
df = df[['TIME', 'MONEY']].dropna()
df['TIME'] = pd.to_datetime(df['TIME'], errors='coerce')  # Intentar convertir TIME si es fecha
df = df.dropna()

series = df['MONEY']

# 3. Graficar la serie
plt.figure(figsize=(10, 4))
plt.plot(series)
plt.title('Serie MONEY (M1 money supply)')
plt.xlabel('Tiempo (índice)')
plt.ylabel('MONEY')
plt.grid()
plt.show()

# 4. Prueba de estacionariedad (ADF)
result = adfuller(series)
print("ADF Statistic:", result[0])
print("p-value:", result[1])

# 5. Diferenciar si no es estacionaria
if result[1] > 0.05:
    series_diff = series.diff().dropna()
    d = 1
else:
    series_diff = series
    d = 0

# 6. Graficar ACF y PACF
plot_acf(series_diff, lags=20)
plot_pacf(series_diff, lags=20)
plt.show()

# 7. Ajustar un modelo ARIMA (1,d,1) como punto de partida
model = ARIMA(series, order=(1, d, 1))
model_fit = model.fit()
print(model_fit.summary())

# 8. Residuos
residuals = model_fit.resid
plt.figure(figsize=(10, 4))
plt.plot(residuals)
plt.title('Residuos del modelo ARIMA')
plt.grid()
plt.show()

# 9. Pronóstico
forecast = model_fit.forecast(steps=10)
print("Pronóstico para los próximos 10 periodos:")
print(forecast)